export const PLACE_CATEGORIES = [
  { id: 'all',           label: 'All',           emoji: '🌍' },
  { id: 'Waterfalls',    label: 'Waterfalls',    emoji: '💧' },
  { id: 'Temples',       label: 'Temples',       emoji: '🛕' },
  { id: 'Beaches',       label: 'Beaches',       emoji: '🏖️' },
  { id: 'Mountains',     label: 'Mountains',     emoji: '⛰️' },
  { id: 'Forests',       label: 'Forests',       emoji: '🌲' },
  { id: 'Historical',    label: 'Historical',    emoji: '🏛️' },
  { id: 'Forts',         label: 'Forts',         emoji: '🏰' },
  { id: 'Wildlife',      label: 'Wildlife',      emoji: '🐘' },
  { id: 'Lakes',         label: 'Lakes',         emoji: '🏞️' },
  { id: 'Caves',         label: 'Caves',         emoji: '🪨' },
  { id: 'Parks',         label: 'Parks',         emoji: '🌿' },
  { id: 'National Parks',label: 'National Parks',emoji: '🏕️' },
  { id: 'Museums',       label: 'Museums',       emoji: '🏫' },
  { id: 'Attractions',   label: 'Attractions',   emoji: '⭐' },
  { id: 'Viewpoints',    label: 'Viewpoints',    emoji: '🔭' },
  { id: 'Mosques',       label: 'Mosques',       emoji: '🕌' },
  { id: 'Churches',      label: 'Churches',      emoji: '⛪' },
  { id: 'Gurudwaras',    label: 'Gurudwaras',    emoji: '🙏' },
  { id: 'Monasteries',   label: 'Monasteries',   emoji: '🧘' },
  { id: 'Dams',          label: 'Dams',          emoji: '🌊' },
  { id: 'Islands',       label: 'Islands',       emoji: '🏝️' },
  { id: 'Bridges',       label: 'Bridges',       emoji: '🌉' },
  { id: 'Airports',      label: 'Airports',      emoji: '✈️' },
  { id: 'Railway Stations', label: 'Railway Stations', emoji: '🚂' },
  { id: 'Bus Stations',  label: 'Bus Stations',  emoji: '🚌' },
  { id: 'Monuments',     label: 'Monuments',     emoji: '🗿' },
  { id: 'Hotels',        label: 'Hotels',        emoji: '🏨' },
  { id: 'Restaurants',   label: 'Restaurants',   emoji: '🍴' },
  { id: 'Cities',        label: 'Cities',        emoji: '🏙️' },
  { id: 'Villages',      label: 'Villages',      emoji: '🏘️' },
  // Experience / Status tags
  { id: 'UNESCO',        label: 'UNESCO',        emoji: '🏆' },
  { id: 'Adventure',     label: 'Adventure',     emoji: '🧗' },
  { id: 'Photography',   label: 'Photography',   emoji: '📸' },
  { id: 'Camping',       label: 'Camping',       emoji: '⛺' },
  { id: 'Family',        label: 'Family',        emoji: '👨‍👩‍👧‍👦' },
  { id: 'Nightlife',     label: 'Nightlife',     emoji: '🌃' },
  { id: 'Food',          label: 'Food',          emoji: '🍽️' },
  { id: 'Shopping',      label: 'Shopping',      emoji: '🛍️' },
  { id: 'Other',         label: 'Other',         emoji: '📍' },
];

export const CATEGORY_COLORS = {
  Waterfalls:     '#3B82F6',
  Temples:        '#F59E0B',
  Beaches:        '#06B6D4',
  Mountains:      '#8B5CF6',
  Forests:        '#10B981',
  Historical:     '#D97706',
  Forts:          '#B45309',
  Wildlife:       '#EF4444',
  Lakes:          '#0EA5E9',
  Caves:          '#6B7280',
  Parks:          '#22C55E',
  'National Parks':'#16A34A',
  Museums:        '#EC4899',
  Attractions:    '#F97316',
  Viewpoints:     '#A78BFA',
  Mosques:        '#059669',
  Churches:       '#7C3AED',
  Gurudwaras:     '#E88D2A',
  Monasteries:    '#D946EF',
  Dams:           '#0284C7',
  Islands:        '#14B8A6',
  Bridges:           '#64748B',
  Airports:          '#3B82F6',
  'Railway Stations': '#9333EA',
  'Bus Stations':    '#7C3AED',
  Monuments:         '#D97706',
  Hotels:            '#0891B2',
  Restaurants:       '#DC2626',
  Cities:            '#64748B',
  Villages:          '#84CC16',
  UNESCO:            '#F59E0B',
  Adventure:         '#EF4444',
  Photography:       '#8B5CF6',
  Camping:           '#059669',
  Family:            '#EC4899',
  Nightlife:         '#7C3AED',
  Food:              '#F97316',
  Shopping:          '#06B6D4',
  Other:             '#6B7280',
};

export const RATING_LABELS = {
  1: 'Terrible',
  2: 'Very Bad',
  3: 'Bad',
  4: 'Below Average',
  5: 'Average',
  6: 'Good',
  7: 'Very Good',
  8: 'Excellent',
  9: 'Outstanding',
  10: 'Perfect',
};

export const MAP_DEFAULTS = {
  center: [20.5937, 78.9629], // India center
  zoom: 5,
  tileUrl: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
  tileAttribution:
    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>',
};

export const SORT_OPTIONS = [
  { id: 'name_asc',   label: 'Name (A–Z)' },
  { id: 'name_desc',  label: 'Name (Z–A)' },
  { id: 'rating_desc',label: 'Top Rated' },
  { id: 'recent',     label: 'Recently Added' },
];

export const PAGE_SIZE = 50;
